CREATE TABLE saque(
	id BIGINT(20)  PRIMARY KEY AUTO_INCREMENT,
	codigo_saque VARCHAR(40) NOT NULL,
	valor_saque  VARCHAR(25) NOT NULL,
	data_saque   TIMESTAMP,
	id_conta BIGINT(20)  NOT NULL,
	FOREIGN KEY (id_conta) REFERENCES conta (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;